import {UnauthorizedAccountError} from "../error/UnauthorizedAccountError";


export class MessageUtil {
    static REGISTRY_SUCCESS_CREATED: string = 'REGISTRY_SUCCESS_CREATED';
    static REGISTRY_SUCCESS_UPDATED: string = 'REGISTRY_SUCCESS_UPDATED';
    static REGISTRY_SUCCESS_DELETE: string = 'REGISTRY_SUCCESS_DELETE';
    //static REGISTRY_SUCCESS_CREATED: string = 'REGISTRY_SUCCESS_CREATED';
    static INVALID_LOGIN_OR_PASSWORD: string = 'INVALID_LOGIN_OR_PASSWORD';
    static INVALID_TWO_FACTOR_CODE: string = 'INVALID_TWO_FACTOR_CODE';
    static INVALID_ACCOUNT_INFORMATION: string = 'INVALID_ACCOUNT_INFORMATION';
    static UNAUTHORIZED_ACCOUNT_ERROR: string = 'UNAUTHORIZED_ACCOUNT_ERROR';
    static INTERNAL_SERVER_ERROR: string = 'INTERNAL_SERVER_ERROR';
    static CREATE_ERROR_DATA: string = 'CREATE_ERROR_DATA';
    static CREATE_TRANSACTION_ERROR_DATA: string = 'CREATE_TRANSACTION_ERROR_DATA';
    static UPDATE_ERROR_DATA: string = 'UPDATE_ERROR_DATA';
    static UPDATE_TRANSACTION_ERROR_DATA: string = 'UPDATE_TRANSACTION_ERROR_DATA';
    static LIST_ERROR_DATA: string = 'LIST_ERROR_DATA';
    static FIND_ERROR_DATA: string = 'FIND_ERROR_DATA';
    static DELETE_ERROR_DATA: string = 'DELETE_ERROR_DATA';
    static DELETE_TRANSACTION_ERROR_DATA: string = 'DELETE_TRANSACTION_ERROR_DATA';
    static PASSWORD_NOT_MATCH_ERROR: string = 'PASSWORD_NOT_MATCH_ERROR';
    static APPLICATION_VALIDATION_ERROR_DATA: string = 'APPLICATION_VALIDATION_ERROR_DATA';
    static APPLICATION_NOT_FOUND_ELEMENT: string = 'APPLICATION_NOT_FOUND_ELEMENT';
    static APPLICATION_VALIDATION_NO_HAVE_CASH: string = 'APPLICATION_VALIDATION_NO_HAVE_CASH';
    static CPF_EXIST_ERROR: string = 'CPF_EXIST_ERROR';
    static EMAIL_EXIST_ERROR: string = 'EMAIL_EXIST_ERROR';
    static USERNAME_EXIST_ERROR: string = 'USERNAME_EXIST_ERROR';
    static INSTANT_TREATMENT_NOT_HABILITED: string = 'INSTANT_TREATMENT_NOT_HABILITED';
}
